name: 2022Assignment2
version: 0.1.0.0
github: "githubuser/2022Assignment2"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/2022Assignment2#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6 && < 1

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wextra
  - -Wno-compat-unqualified-imports

library:
  source-dirs:
    - src
    - submission
  default-extensions:
    - NamedFieldPuns

executables:
  2022Assignment2-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: []
    dependencies:
      - 2022Assignment2

tests:
  2022Assignment2-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: []
    dependencies:
      - 2022Assignment2
      - QuickCheck
      - Glob
      - doctest
      - fsnotify
      - ansi-terminal
